---

- name: Girder
  user: ubuntu
  hosts: tag_type_girder
  gather_facts: false
  vars:
    girder_admin_user: cpatrick
    # need to pass this in externally
    #girder_admin_password:
    girder_admin_email: patrick.reynolds@kitware.com
    girder_socket_host: localhost
    girder_socket_port: 8080
    girder_plugins: []

  roles:
    - users
    - common
    - mongodb
    - girder

